#
# $FreeBSD: head/en_US.ISO8859-1/articles/freebsd-releng/Makefile 51066 2017-10-06 14:08:45Z wosch $
#
# Article: FreeBSD Release Engineering

DOC?=		article

FORMATS?=	html html-split

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS=		article.xml

CSS_SHEET_ADDITIONS=extra.css

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"

